### PR TITLE
iframe id issue fixed

### PR DESCRIPTION
**Pull request by Raghav888**

### CODE REVIEW

**Review by fahd23 — APPROVED** [review]
Seems good to me

**Review by JantuDeb — APPROVED** [review]
CSS is looking good. I would suggest that you add a component name in the title for the pull request. If this is pull request is for documentation then you don't need to review I guess.

**Comment by ShreyashMahajan** [comment]
according to me, it's good.

**Comment by ShreyashMahajan** [comment]
according to me, it's very good

**Pull request merged**
